In [1]:
import numpy as np

In [2]:
#creating a 1-dimensional array
a=np.array([1,2,3,4,5])

In [3]:
#print it
print(a)

[1 2 3 4 5]


In [5]:
#let us create 2-dimensional array
b=np.array([[1,2,3],[4,5,6]])
#printing 2-dimensional array
print(b)

[[1 2 3]
 [4 5 6]]


In [6]:
#creating an array of zeros
c=np.zeros((3,4))#we specify the dimensions of array
#printIng array of zeros
print(c)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
#creating an array of ones
d=np.ones((2,2))
#printing array of ones
print(d)

[[1. 1.]
 [1. 1.]]


In [8]:
#adding two arrays
a=np.array([1,2,3])
b=np.array([4,5,6])
c=a+b
print(c)

[5 7 9]


In [9]:
#multiplication of two arrays
g=np.array([[1,2],[3,4]])
h=np.array([[5,6],[7,8]])
i=np.dot(g,h)
print(i)

[[19 22]
 [43 50]]
